services:
  - type: web
    name: doguinha-store-bot
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: BOT_NAME
        value: Doguinha Store
      - key: ADMIN_NUMBER
        value: 5511999999999
      - key: SUPPORT_TELEGRAM
        value: "@doguinhastore"
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: MP_PUBLIC_KEY
        sync: false
      - key: COMMISSION_PERCENTAGE
        value: "10"
      - key: PIX_EXPIRATION
        value: "30"
      - key: DB_PATH
        value: /opt/render/project/src/database/store.db
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
